# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_info',
                'abstract': False,
                'ordering': ['label'],
            },
        ),
    ]
