# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160913_0433'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('peeps', django.db.models.manager.Manager()),
            ],
        ),
    ]
