# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_opinionpoll_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('A', 'Author'), ('E', 'Editor')], default='E', max_length=1),
        ),
    ]
