# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_anotherperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anotherperson',
            old_name='second',
            new_name='last',
        ),
    ]
