# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 08:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 9, 22, 8, 57, 37, 667736, tzinfo=utc))),
            ],
        ),
    ]
